// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React$Frp = require("../react/src/react.bs.js");

function eventFromPromise(promise) {
  var match = React$Frp.E.create(undefined);
  var promiseF = match[1];
  promise.then(function (x) {
          Curry._2(promiseF, undefined, {
                TAG: /* Ok */0,
                _0: x
              });
          return promise;
        }).catch(function (x) {
        Curry._2(promiseF, undefined, {
              TAG: /* Error */1,
              _0: x
            });
        return promise;
      });
  return match[0];
}

function join(ee) {
  return React$Frp.E.$$switch(React$Frp.E.never, ee);
}

function bind(e, f) {
  return join(React$Frp.E.map(f, e));
}

var $$Event = {
  join: join,
  bind: bind
};

var Utils = {
  eventFromPromise: eventFromPromise,
  $$Event: $$Event
};

exports.Utils = Utils;
/* React-Frp Not a pure module */
